# Generated by Django 5.2 on 2025-04-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("Movie_id", models.IntegerField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=30)),
                ("Rating", models.IntegerField()),
                ("Language", models.CharField()),
                ("Genre", models.CharField(max_length=20)),
                ("noofseats", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
